- hosts: master
  become: yes
  roles:
    - mesosphere-repository
    - zookeeper
    - mesos
    - marathon
    - chronos

- hosts: slave
  become: yes
  roles:
    - mesosphere-repository
    - mesos
